export const uiContract = Object.freeze({
  contractVersion: '1.0.0',
  renderer: 'amis@6.7',
  colorScheme: 'light',
});

export const designTokens = Object.freeze({
  '--zv-primary': '#4f6ef7',
  '--zv-primary-rgb': '79 110 247',
  '--zv-primary-hover': '#6682ff',
  '--zv-primary-pressed': '#3f5bd8',
  '--zv-primary-soft': 'rgba(79, 110, 247, 0.11)',
  '--zv-cyan': '#22b8cf',
  '--zv-cyan-rgb': '34 184 207',
  '--zv-cyan-pressed': '#1595ab',
  '--zv-success': '#12b981',
  '--zv-success-rgb': '18 185 129',
  '--zv-success-pressed': '#0f9f70',
  '--zv-warning': '#f59e0b',
  '--zv-warning-rgb': '245 158 11',
  '--zv-danger': '#ef476f',
  '--zv-danger-rgb': '239 71 111',
  '--zv-danger-pressed': '#d93b61',
  '--zv-info': '#2f80ed',
  '--zv-info-rgb': '47 128 237',
  '--zv-text-on-accent': '#ffffff',
  '--zv-on-accent-rgb': '255 255 255',
  '--zv-shadow-rgb': '15 23 42',
  '--zv-overlay-rgb': '8 15 30',
  '--zv-bg': '#f4f7fb',
  '--zv-bg-canvas': '#f4f7fb',
  '--zv-bg-canvas-rgb': '244 247 251',
  '--zv-bg-elevated': '#ffffff',
  '--zv-bg-surface': '#ffffff',
  '--zv-bg-surface-rgb': '255 255 255',
  '--zv-bg-subtle': '#f8faff',
  '--zv-bg-muted': '#f8faff',
  '--zv-text': '#172033',
  '--zv-text-primary': '#172033',
  '--zv-text-secondary': '#5f6b7e',
  '--zv-text-muted': '#8b97aa',
  '--zv-text-tertiary': '#8b97aa',
  '--zv-sidebar': '#111a2e',
  '--zv-sidebar-raised': '#1b2941',
  '--zv-sidebar-text': '#c8d2e2',
  '--zv-border': '#e2e8f2',
  '--zv-border-rgb': '226 232 242',
  '--zv-border-strong': '#d3dbe8',
  '--zv-divider': '#e9eef6',
  '--zv-header': 'rgba(255, 255, 255, 0.88)',
  '--zv-sidebar-hover': 'rgba(255, 255, 255, 0.08)',
  '--zv-radius-sm': '9px',
  '--zv-radius': '12px',
  '--zv-radius-lg': '16px',
  '--zv-shadow-sm': '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 14px rgba(15, 23, 42, 0.04)',
  '--zv-shadow-md': '0 12px 32px rgba(15, 23, 42, 0.08)',
  '--zv-shadow-lg': '0 24px 64px rgba(15, 23, 42, 0.13)',
  '--zv-motion': 'cubic-bezier(0.2, 0.8, 0.2, 1)',
  '--zv-space-1': '4px',
  '--zv-space-2': '8px',
  '--zv-space-3': '12px',
  '--zv-space-4': '16px',
  '--zv-space-5': '20px',
  '--zv-space-6': '24px',
  '--zv-space-8': '32px',
  '--zv-font-family': `Inter, 'Alibaba PuHuiTi', 'PingFang SC', 'Microsoft YaHei', system-ui, sans-serif`,
  '--zv-aside-width': 'clamp(196px, 14vw, 228px)',
  '--zv-header-height': '68px',
  '--zv-canvas': 'var(--zv-bg-canvas)',
  '--zv-surface': 'var(--zv-bg-surface)',
  '--zv-surface-raised': 'var(--zv-bg-elevated)',
  '--zv-surface-muted': 'var(--zv-bg-muted)',
  '--zv-shadow': 'var(--zv-shadow-md)',
  '--zv-ease': 'var(--zv-motion)',
  '--zv-ease-out': 'var(--zv-motion)',
});

export const elementTokens = Object.freeze({
  '--el-color-primary': designTokens['--zv-primary'],
  '--el-color-primary-light-3': designTokens['--zv-primary-hover'],
  '--el-color-primary-dark-2': designTokens['--zv-primary-pressed'],
  '--el-color-success': designTokens['--zv-success'],
  '--el-color-warning': designTokens['--zv-warning'],
  '--el-color-danger': designTokens['--zv-danger'],
  '--el-color-info': designTokens['--zv-info'],
  '--el-bg-color': designTokens['--zv-bg-surface'],
  '--el-bg-color-page': designTokens['--zv-bg-canvas'],
  '--el-text-color-primary': designTokens['--zv-text-primary'],
  '--el-text-color-regular': designTokens['--zv-text-secondary'],
  '--el-text-color-secondary': designTokens['--zv-text-muted'],
  '--el-border-color': designTokens['--zv-border'],
  '--el-border-radius-base': designTokens['--zv-radius-sm'],
});

export const naiveTokens = Object.freeze({
  primaryColor: designTokens['--zv-primary'],
  primaryColorHover: designTokens['--zv-primary-hover'],
  primaryColorPressed: designTokens['--zv-primary-pressed'],
  primaryColorSuppl: designTokens['--zv-primary-hover'],
  infoColor: designTokens['--zv-info'],
  successColor: designTokens['--zv-success'],
  warningColor: designTokens['--zv-warning'],
  errorColor: designTokens['--zv-danger'],
  bodyColor: designTokens['--zv-bg-canvas'],
  cardColor: designTokens['--zv-bg-surface'],
  modalColor: designTokens['--zv-bg-surface'],
  popoverColor: designTokens['--zv-bg-surface'],
  tableColor: designTokens['--zv-bg-surface'],
  inputColor: designTokens['--zv-bg-surface'],
  actionColor: designTokens['--zv-bg-subtle'],
  textColorBase: designTokens['--zv-text-primary'],
  borderColor: designTokens['--zv-border'],
  dividerColor: designTokens['--zv-divider'],
  borderRadius: designTokens['--zv-radius'],
  borderRadiusSmall: designTokens['--zv-radius-sm'],
  fontFamily: designTokens['--zv-font-family'],
  fontSize: '14px',
  boxShadow1: designTokens['--zv-shadow-sm'],
  boxShadow2: designTokens['--zv-shadow-md'],
  boxShadow3: designTokens['--zv-shadow-lg'],
});

export const chartPalette = Object.freeze({
  primary: designTokens['--zv-primary'],
  cyan: designTokens['--zv-cyan'],
  success: designTokens['--zv-success'],
  warning: designTokens['--zv-warning'],
  danger: designTokens['--zv-danger'],
  heading: designTokens['--zv-text-primary'],
  text: designTokens['--zv-text-secondary'],
  muted: designTokens['--zv-text-muted'],
  line: designTokens['--zv-border-strong'],
  split: '#edf1f6',
  surface: 'transparent',
  pieBorder: designTokens['--zv-bg-surface'],
});

export const pluginClasses = Object.freeze([
  'zv-page',
  'zv-workspace',
  'zv-visual-page',
  'zv-crud-workspace',
  'zv-hero',
  'zv-hero__chips',
  'zv-hero__status',
  'zv-summary-bar',
  'zv-summary-metric',
  'zv-summary-copy',
  'zv-metric-card',
  'zv-chart-card',
  'zv-table-shell',
  'zv-truncate',
  'zv-wrap',
]);
